version: '3.8'

services:

  nginx_service:
    image: nginx

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./static/:/home/app/web/staticfiles/
      - static_data:/home/app/web/staticfiles/

    depends_on:
      - django_service

    container_name: nginx_service_con

  django_service:

    build: ./

    volumes:
      - static_data:/app/static/
      - ./djangoDeployProject/settings.py:/app/djangoDeployProject/settings.py

#    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

#    ports:
#      - "8000:8000"

    container_name: django_service_con

volumes:
  static_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: ./static
      o: bind
#
#  db_data:
#    driver: local
#    driver_opts:
#      type: none
#      device: /data/db_data
#      o: bind